### ISSUE TITLE
undefined symbol: _ZN3c106detail14torchCheckFailEPKcS2_jS2_

### ISSUE THREAD

**Issue by Weixin-An** [watml/fast-wasserstein-adversarial#2]
Recently, I have read this paper and code. However, I have a question about them. When I run "python train.py", there is the following bug: ...undefined symbol: _ZN3c106detail14torchCheckFailEPKcS2_jS2_. Is this because of my CUDA version？ Thank you very much.

**Comment by kayween** [comment]
Hi,

It seems that there are some issues in the /sparse_tensor package installation.
Can you make sure the torch version is exactly 1.5.1 and reinstall the  sparse_tensor package again?

Kaiwen
